name: "Bug Report"
description: Submit a bug report
labels: [ "bug" ]
body:
  - type: input
    id: branch
    attributes:
      label: Branch/Tag/Commit
      description:
      placeholder: ex,. main
    validations:
      required: true
  - type: input
    id: docker_image_version
    attributes:
      label: Docker Image Version
      description:
      placeholder: ex,. nvcr.io/nvidia/pytorch:22.08-py3
    validations:
      required: true
  - type: input
    id: gpu_name
    attributes:
      label: GPU name
      description:
      placeholder: ex,. A100
    validations:
      required: true
  - type: input
    id: cuda_driver
    attributes:
      label: CUDA Driver
      description:
      placeholder: ex,. 515.65.01
    validations:
      required: true

  - type: textarea
    id: reproduced-steps
    attributes:
      label: Reproduced Steps
      description: Please provide the step to reproduce the bugs
      render: shell
      placeholder: |
        Steps to reproduce your bugs: (please list what script you run and don't say following xxx, otherwise, we will ask again and again)

        1. docker run -ti --gpus all nvcr.io/nvidia/pytorch:22.03-py3 bash
        2. git clone https://github.com/NVIDIA/FasterTransformer.git
        3. cd FasterTransformer mkdir build && cd build
        4. cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release .. && make -j12
        5. ./bin/bert_example 32 12 32 12 64 0 0
        6. What error you see.
  
    validations:
      required: true
